import { createClient } from 'npm:@insforge/sdk';

export default async function (req) {
    const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    };

    if (req.method === 'OPTIONS') {
        return new Response(null, { status: 204, headers: corsHeaders });
    }

    const client = createClient({
        baseUrl: Deno.env.get('INSFORGE_BASE_URL'),
        anonKey: Deno.env.get('ANON_KEY'),
    });

    try {
        // ========== POST: Create a new order ==========
        if (req.method === 'POST') {
            const body = await req.json();
            console.log('Incoming Order Request Body:', JSON.stringify(body, null, 2));
            const { templateId, email, formValues, paymentMethod, userId, userImageUrl, userVideoUrl } = body;

            if (!templateId || !email || !formValues) {
                return new Response(JSON.stringify({ error: 'Missing required fields: templateId, email, formValues' }), {
                    status: 400,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            // 1. Fetch the template
            const { data: template, error: templateErr } = await client.database
                .from('templates')
                .select('*')
                .eq('id', templateId)
                .single();

            if (templateErr || !template) {
                return new Response(JSON.stringify({ error: 'Template not found', details: templateErr?.message }), {
                    status: 404,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            // 2. Build the prompts from skeletons + form values
            let constructedVideoPrompt = template.video_prompt_skeleton || '';
            let constructedImagePrompt = template.image_prompt_skeleton || '';

            for (const [key, value] of Object.entries(formValues)) {
                const regex = new RegExp(`\\{${key}\\}`, 'gi');
                constructedVideoPrompt = constructedVideoPrompt.replace(regex, value);
                constructedImagePrompt = constructedImagePrompt.replace(regex, value);
            }

            // 3. Create the order — readable_id is auto-generated by DB trigger
            const orderInsert = {
                template_id: templateId,
                email,
                user_id: userId || null,
                form_values: formValues,
                amount: template.price,
                payment_method: paymentMethod || 'stripe',
                payment_status: 'pending',
                generation_status: 'pending',
                constructed_video_prompt: constructedVideoPrompt,
                constructed_image_prompt: constructedImagePrompt,
                constructed_prompt: constructedVideoPrompt,
                template_type: template.template_type || 'video',
                reference_image_url: userImageUrl || template.reference_image_url || null,
                user_video_url: userVideoUrl || null,
            };

            const { data: order, error: orderErr } = await client.database
                .from('orders')
                .insert([orderInsert])
                .select()
                .single();

            if (orderErr) {
                console.error('Order insert error:', orderErr);
                return new Response(JSON.stringify({ error: 'Failed to create order', details: orderErr.message }), {
                    status: 500,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            return new Response(JSON.stringify({
                success: true,
                order: {
                    id: order.id,
                    readable_id: order.readable_id,
                    amount: order.amount,
                    payment_status: order.payment_status,
                    generation_status: order.generation_status,
                },
            }), {
                status: 201,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            });
        }

        // ========== GET: Poll order status ==========
        if (req.method === 'GET') {
            const url = new URL(req.url);
            const orderId = url.searchParams.get('orderId');

            if (!orderId) {
                return new Response(JSON.stringify({ error: 'orderId query param required' }), {
                    status: 400,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            const { data: order, error } = await client.database
                .from('orders')
                .select('id, readable_id, email, amount, payment_status, generation_status, video_url, created_at, template_type, reference_image_url, generated_image_url')
                .eq('id', orderId)
                .single();

            if (error || !order) {
                return new Response(JSON.stringify({ error: 'Order not found' }), {
                    status: 404,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            return new Response(JSON.stringify({ order }), {
                status: 200,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            });
        }

        // ========== PUT: Payment confirmation + trigger generation ==========
        if (req.method === 'PUT') {
            const body = await req.json();
            const { orderId, action, confirmDecision } = body;

            if (!orderId) {
                return new Response(JSON.stringify({ error: 'orderId required' }), {
                    status: 400,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            if (action === 'confirm-payment') {
                const { data: order } = await client.database
                    .from('orders')
                    .select('*')
                    .eq('id', orderId)
                    .single();

                let template = null;
                if (order?.template_id) {
                   const { data: t } = await client.database.from('templates').select('*').eq('id', order.template_id).single();
                   if (t) template = t;
                }
                
                let aiModel = (template?.ai_model || template?.aiModel || '').toLowerCase();
                if (!aiModel) {
                    if (order?.form_values?.seedance_user_images) aiModel = 'seedance_2_5_v2';
                    else if (order?.form_values?.kling_video_url) aiModel = 'kling_3_0_v2';
                }
                const isDirectVideoModel = aiModel.includes('seedance') || aiModel.includes('kling');

                const hasRefImage = !!order?.reference_image_url;
                const isImageOnly = (template?.template_type === 'image' || order?.template_type === 'image') && !isDirectVideoModel;
                
                // For Seedance and Kling, the uploaded images/videos are used directly for generation.
                // We do NOT want to pass them through Nano Banana first.
                const startStatus = (isImageOnly || (hasRefImage && !isDirectVideoModel)) ? 'generating_image' : 'generating';

                // ⚡ ATOMIC CONCURRENCY LOCK: Update ONLY if payment_status is still 'pending'
                let didClaim = false;
                if (order?.payment_status === 'pending') {
                    const { data: updatedOrders, error: updateErr } = await client.database
                        .from('orders')
                        .update({ payment_status: 'paid', generation_status: startStatus, updated_at: new Date().toISOString() })
                        .eq('id', orderId)
                        .eq('payment_status', 'pending')
                        .select();

                    if (updateErr) console.error('Update payment error:', updateErr);
                    if (updatedOrders && updatedOrders.length > 0) didClaim = true;
                } else if (order?.payment_status === 'paid') {
                    didClaim = true;
                }

                if (!didClaim) {
                    console.log(`[LOCK] Order ${orderId} already claimed by concurrent thread in process-order. Skipping duplicate execution.`);
                    return new Response(JSON.stringify({ success: true, message: 'Already claimed by concurrent thread' }), {
                        status: 200,
                        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
                    });
                }

                // Determine Router
                const getTargetFunction = (type, currentModel) => {
                    if (type === 'image') {
                        if (currentModel === 'nano_banana_pro_v2') return 'generate-image-nano-v2';
                        return 'generate-image';
                    }
                    if (type === 'video') {
                        if (currentModel === 'veo_3_1_v2') return 'generate-video-veo-v2';
                        if (currentModel.includes('kling')) return 'generate-video-kling-v2';
                        if (currentModel.includes('seedance')) return 'generate-video-seedance-v2';
                        return 'generate-video';
                    }
                    return 'generate-video';
                };

                try {
                    if (startStatus === 'generating_image') {
                        const targetFunc = getTargetFunction('image', aiModel);
                        await client.functions.invoke(targetFunc, { body: { orderId, action: 'submit' } });
                    } else {
                        const targetFunc = getTargetFunction('video', aiModel);
                        await client.functions.invoke(targetFunc, { body: { orderId, action: 'submit' } });
                    }
                } catch (e) {
                    console.error('Failed to trigger generation:', e);
                }

                return new Response(JSON.stringify({
                    success: true,
                    message: 'Payment confirmed. Generation started.',
                    status: startStatus,
                }), {
                    status: 200,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            if (action === 'poll') {
                const { data: order } = await client.database
                    .from('orders')
                    .select('*')
                    .eq('id', orderId)
                    .single();

                let template = null;
                if (order?.template_id) {
                    const { data: t } = await client.database.from('templates').select('*').eq('id', order.template_id).single();
                    if (t) template = t;
                }
                let aiModel = (template?.ai_model || template?.aiModel || '').toLowerCase();
                if (!aiModel && order?.form_values?.seedance_user_images) aiModel = 'seedance_2_5_v2';

                const getTargetFunction = (type, currentModel) => {
                    if (type === 'image') {
                        if (currentModel === 'nano_banana_pro_v2') return 'generate-image-nano-v2';
                        return 'generate-image'; 
                    } else {
                        if (currentModel === 'veo_3_1_v2') return 'generate-video-veo-v2';
                        if (currentModel.includes('kling')) return 'generate-video-kling-v2';
                        if (currentModel.includes('seedance')) return 'generate-video-seedance-v2';
                        return 'generate-video';
                    }
                };

                try {
                    const type = order.generation_status === 'generating_image' ? 'image' : 'video';
                    const targetFunc = getTargetFunction(type, aiModel);
                    
                    const { data, error } = await client.functions.invoke(targetFunc, { body: { orderId, action: 'poll' } });
                    if (error) throw error;

                    return new Response(JSON.stringify(data), {
                        status: 200,
                        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                    });
                } catch (e) {
                    console.error('Failed to poll generation:', e);
                    const msg = e instanceof Error ? e.message : String(e);
                    return new Response(JSON.stringify({ error: 'Failed to route poll request', details: msg }), {
                        status: 500,
                        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                    });
                }
            }

            if (action === 'confirm-image') {
                const { data: order } = await client.database
                    .from('orders')
                    .select('template_type, generated_image_url, templates(*)')
                    .eq('id', orderId)
                    .single();

                if (!order) {
                    return new Response(JSON.stringify({ error: 'Order not found' }), {
                        status: 404,
                        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                    });
                }

                const isImageOnly = order.template_type === 'image';
                const finalStatus = isImageOnly ? 'completed' : 'generating';

                if (confirmDecision === 'approve') {
                    await client.database
                        .from('orders')
                        .update({
                            generation_status: finalStatus,
                            image_confirmation_status: 'approved',
                            video_url: isImageOnly ? order.generated_image_url : null,
                            updated_at: new Date().toISOString(),
                        })
                        .eq('id', orderId);

                    if (!isImageOnly) {
                        try {
                            const template = Array.isArray(order?.templates) ? order.templates[0] : order?.templates;
                            const aiModel = (template?.ai_model || template?.aiModel || '').toLowerCase();
                            const getTargetFunction = (currentModel) => {
                                if (!currentModel || currentModel === 'veo_3_1' || currentModel === 'nano_banana_pro' || currentModel === 'kling_3_0') return 'generate-video';
                                if (currentModel === 'veo_3_1_v2') return 'generate-video-veo-v2';
                                if (currentModel.includes('kling')) return 'generate-video-kling-v2';
                                if (currentModel.includes('seedance')) return 'generate-video-seedance-v2';
                                return 'generate-video';
                            };
                            const targetFunc = getTargetFunction(aiModel);
                            await client.functions.invoke(targetFunc, { body: { orderId, action: 'submit' } });
                        } catch (e) {
                            console.error('Failed to trigger video generation:', e);
                        }
                    }

                    return new Response(JSON.stringify({ success: true, status: finalStatus }), {
                        status: 200,
                        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                    });
                } else if (confirmDecision === 'regenerate') {
                    await client.database
                        .from('orders')
                        .update({
                            generation_status: 'generating_image',
                            generated_image_url: null,
                            image_task_id: null,
                            updated_at: new Date().toISOString(),
                        })
                        .eq('id', orderId);

                    try {
                        const template = Array.isArray(order?.templates) ? order.templates[0] : order?.templates;
                        const aiModel = (template?.ai_model || template?.aiModel || '').toLowerCase();
                        const getTargetFunction = (currentModel) => {
                            if (!currentModel || currentModel === 'veo_3_1' || currentModel === 'nano_banana_pro' || currentModel === 'kling_3_0') return 'generate-image';
                            if (currentModel === 'nano_banana_pro_v2') return 'generate-image-nano-v2';
                            // If Veo needs to regenerate its image
                            if (currentModel === 'veo_3_1_v2') return 'generate-image'; // Or keep it simple since we didn't make a separate image generator for veo yet, but let's route to legacy generate-image which handles prompts for Veo intermediate.
                            return 'generate-image';
                        };
                        const targetFunc = getTargetFunction(aiModel);
                        await client.functions.invoke(targetFunc, { body: { orderId, action: 'submit', force: true } });
                    } catch (e) {
                        console.error('Failed to trigger image regeneration:', e);
                    }

                    return new Response(JSON.stringify({ success: true, status: 'generating_image' }), {
                        status: 200,
                        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                    });
                }
            }

            return new Response(JSON.stringify({ error: 'Unknown action' }), {
                status: 400,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            });
        }

        return new Response(JSON.stringify({ error: 'Method not allowed' }), {
            status: 405,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
    } catch (err) {
        console.error('Unhandled error:', String(err));
        return new Response(JSON.stringify({ error: 'Internal server error', details: String(err), stack: err instanceof Error ? err.stack : undefined }), {
            status: 500,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
    }
}
