import { createClient } from 'npm:@insforge/sdk';

export default async function (req) {
    const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    };

    if (req.method === 'OPTIONS') {
        return new Response(null, { status: 204, headers: corsHeaders });
    }

    const client = createClient({
        baseUrl: Deno.env.get('INSFORGE_BASE_URL'),
        anonKey: Deno.env.get('ANON_KEY'),
    });

    try {
        // ========== POST: Create a new order ==========
        if (req.method === 'POST') {
            const body = await req.json();
            const { templateId, email, formValues, paymentMethod, userId, userImageUrl } = body;

            if (!templateId || !email || !formValues) {
                return new Response(JSON.stringify({ error: 'Missing required fields: templateId, email, formValues' }), {
                    status: 400,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            // 1. Fetch the template
            const { data: template, error: templateErr } = await client.database
                .from('templates')
                .select('*')
                .eq('id', templateId)
                .single();

            if (templateErr || !template) {
                return new Response(JSON.stringify({ error: 'Template not found', details: templateErr?.message }), {
                    status: 404,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            // 2. Build the prompts from skeletons + form values
            let constructedVideoPrompt = template.video_prompt_skeleton || '';
            let constructedImagePrompt = template.image_prompt_skeleton || '';

            for (const [key, value] of Object.entries(formValues)) {
                const regex = new RegExp(`\\{${key}\\}`, 'gi');
                constructedVideoPrompt = constructedVideoPrompt.replace(regex, value);
                constructedImagePrompt = constructedImagePrompt.replace(regex, value);
            }

            // 3. Create the order — readable_id is auto-generated by DB trigger
            const orderInsert = {
                template_id: templateId,
                email,
                user_id: userId || null,
                form_values: formValues,
                amount: template.price,
                payment_method: paymentMethod || 'stripe',
                payment_status: 'pending',
                generation_status: 'pending',
                constructed_video_prompt: constructedVideoPrompt,
                constructed_image_prompt: constructedImagePrompt,
                constructed_prompt: constructedVideoPrompt,
                template_type: template.template_type || 'video',
                reference_image_url: userImageUrl || template.reference_image_url || null,
            };

            const { data: order, error: orderErr } = await client.database
                .from('orders')
                .insert(orderInsert)
                .select()
                .single();

            if (orderErr) {
                console.error('Order insert error:', orderErr);
                return new Response(JSON.stringify({ error: 'Failed to create order', details: orderErr.message }), {
                    status: 500,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            return new Response(JSON.stringify({
                success: true,
                order: {
                    id: order.id,
                    readable_id: order.readable_id,
                    amount: order.amount,
                    payment_status: order.payment_status,
                    generation_status: order.generation_status,
                },
            }), {
                status: 201,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            });
        }

        // ========== GET: Poll order status ==========
        if (req.method === 'GET') {
            const url = new URL(req.url);
            const orderId = url.searchParams.get('orderId');

            if (!orderId) {
                return new Response(JSON.stringify({ error: 'orderId query param required' }), {
                    status: 400,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            const { data: order, error } = await client.database
                .from('orders')
                .select('id, readable_id, email, amount, payment_status, generation_status, video_url, created_at, template_type, reference_image_url, generated_image_url')
                .eq('id', orderId)
                .single();

            if (error || !order) {
                return new Response(JSON.stringify({ error: 'Order not found' }), {
                    status: 404,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            return new Response(JSON.stringify({ order }), {
                status: 200,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            });
        }

        // ========== PUT: Payment confirmation + trigger generation ==========
        if (req.method === 'PUT') {
            const body = await req.json();
            const { orderId, action, confirmDecision } = body;

            if (!orderId) {
                return new Response(JSON.stringify({ error: 'orderId required' }), {
                    status: 400,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            if (action === 'confirm-payment') {
                const { data: order } = await client.database
                    .from('orders')
                    .select('reference_image_url, template_type')
                    .eq('id', orderId)
                    .single();

                const hasRefImage = !!order?.reference_image_url;
                const isImageOnly = order?.template_type === 'image';
                const startStatus = (hasRefImage || isImageOnly) ? 'generating_image' : 'generating';

                const { error: updateErr } = await client.database
                    .from('orders')
                    .update({ payment_status: 'paid', generation_status: startStatus, updated_at: new Date().toISOString() })
                    .eq('id', orderId);

                if (updateErr) console.error('Update payment error:', updateErr);

                try {
                    if (hasRefImage || isImageOnly) {
                        await client.functions.invoke('generate-image', { body: { orderId, action: 'submit' } });
                    } else {
                        await client.functions.invoke('generate-video', { body: { orderId, action: 'submit' } });
                    }
                } catch (e) {
                    console.error('Failed to trigger generation:', e);
                }

                return new Response(JSON.stringify({
                    success: true,
                    message: 'Payment confirmed. Generation started.',
                    status: startStatus,
                }), {
                    status: 200,
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                });
            }

            if (action === 'confirm-image') {
                const { data: order } = await client.database
                    .from('orders')
                    .select('template_type, generated_image_url')
                    .eq('id', orderId)
                    .single();

                const isImageOnly = order?.template_type === 'image';

                if (confirmDecision === 'approve') {
                    const finalStatus = isImageOnly ? 'completed' : 'generating';
                    await client.database
                        .from('orders')
                        .update({
                            generation_status: finalStatus,
                            updated_at: new Date().toISOString(),
                            video_url: isImageOnly ? order?.generated_image_url : null,
                        })
                        .eq('id', orderId);

                    if (!isImageOnly) {
                        try {
                            await client.functions.invoke('generate-video', { body: { orderId, action: 'submit' } });
                        } catch (e) {
                            console.error('Failed to trigger video generation:', e);
                        }
                    }

                    return new Response(JSON.stringify({ success: true, status: finalStatus }), {
                        status: 200,
                        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                    });
                } else if (confirmDecision === 'regenerate') {
                    await client.database
                        .from('orders')
                        .update({
                            generation_status: 'generating_image',
                            generated_image_url: null,
                            image_task_id: null,
                            updated_at: new Date().toISOString(),
                        })
                        .eq('id', orderId);

                    try {
                        await client.functions.invoke('generate-image', { body: { orderId, action: 'submit', force: true } });
                    } catch (e) {
                        console.error('Failed to trigger image regeneration:', e);
                    }

                    return new Response(JSON.stringify({ success: true, status: 'generating_image' }), {
                        status: 200,
                        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                    });
                }
            }

            return new Response(JSON.stringify({ error: 'Unknown action' }), {
                status: 400,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            });
        }

        return new Response(JSON.stringify({ error: 'Method not allowed' }), {
            status: 405,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
    } catch (err) {
        console.error('Unhandled error:', err);
        return new Response(JSON.stringify({ error: 'Internal server error', details: String(err) }), {
            status: 500,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
    }
}
